{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "187900.87s - pydevd: Sending message related to process being replaced timed-out after 5 seconds\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): failed\n",
      "\n",
      "UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel f <https://conda.anaconda.org/f>\n",
      "\n",
      "The channel is not accessible or is invalid.\n",
      "\n",
      "You will need to adjust your conda configuration to proceed.\n",
      "Use `conda config --show channels` to view your configuration's current state,\n",
      "and use `conda config --show-sources` to view config file locations.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "!conda install -cf conda-forge pyogrio\n",
    "#!pip install geopandas\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "187594.52s - pydevd: Sending message related to process being replaced timed-out after 5 seconds\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: owslib in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (0.31.0)\n",
      "Collecting geopandas\n",
      "  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: matplotlib in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (3.8.4)\n",
      "Collecting ipyleaflet\n",
      "  Using cached ipyleaflet-0.19.2-py3-none-any.whl.metadata (5.3 kB)\n",
      "Requirement already satisfied: lxml in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from owslib) (4.9.1)\n",
      "Requirement already satisfied: python-dateutil>=1.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from owslib) (2.8.2)\n",
      "Requirement already satisfied: pytz in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from owslib) (2024.1)\n",
      "Requirement already satisfied: pyyaml in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from owslib) (6.0.1)\n",
      "Requirement already satisfied: requests>=1.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from owslib) (2.32.2)\n",
      "Requirement already satisfied: numpy>=1.22 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (1.24.3)\n",
      "Collecting pyogrio>=0.7.2 (from geopandas)\n",
      "  Using cached pyogrio-0.9.0.tar.gz (352 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: packaging in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (21.3)\n",
      "Requirement already satisfied: pandas>=1.4.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (1.4.4)\n",
      "Requirement already satisfied: pyproj>=3.3.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/pyproj-3.6.1-py3.10-macosx-10.9-x86_64.egg (from geopandas) (3.6.1)\n",
      "Requirement already satisfied: shapely>=2.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/shapely-2.0.4-py3.10-macosx-10.9-x86_64.egg (from geopandas) (2.0.4)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (4.25.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: pillow>=8 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (9.2.0)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib) (3.0.9)\n",
      "Collecting branca>=0.5.0 (from ipyleaflet)\n",
      "  Using cached branca-0.7.2-py3-none-any.whl.metadata (1.5 kB)\n",
      "Requirement already satisfied: ipywidgets<9,>=7.6.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipyleaflet) (7.6.5)\n",
      "Collecting jupyter-leaflet<0.20,>=0.19 (from ipyleaflet)\n",
      "  Using cached jupyter_leaflet-0.19.2-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting traittypes<3,>=0.2.1 (from ipyleaflet)\n",
      "  Using cached traittypes-0.2.1-py2.py3-none-any.whl.metadata (1.0 kB)\n",
      "Requirement already satisfied: xyzservices>=2021.8.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipyleaflet) (2022.9.0)\n",
      "Collecting jinja2>=3 (from branca>=0.5.0->ipyleaflet)\n",
      "  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (6.15.2)\n",
      "Requirement already satisfied: ipython-genutils~=0.2.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.0)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (5.1.1)\n",
      "Requirement already satisfied: nbformat>=4.2.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (5.1.3)\n",
      "Requirement already satisfied: widgetsnbextension~=3.5.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (3.5.2)\n",
      "Requirement already satisfied: ipython>=4.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (7.31.1)\n",
      "Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyleaflet) (1.0.0)\n",
      "Requirement already satisfied: certifi in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas) (2024.6.2)\n",
      "Requirement already satisfied: six>=1.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from python-dateutil>=1.5->owslib) (1.16.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests>=1.0->owslib) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests>=1.0->owslib) (3.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests>=1.0->owslib) (2.1.0)\n",
      "Requirement already satisfied: appnope in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (0.1.2)\n",
      "Requirement already satisfied: debugpy>=1.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (1.6.7)\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (7.4.9)\n",
      "Requirement already satisfied: matplotlib-inline>=0.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (0.1.6)\n",
      "Requirement already satisfied: nest-asyncio in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (1.6.0)\n",
      "Requirement already satisfied: psutil in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (5.9.0)\n",
      "Requirement already satisfied: pyzmq>=17 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (23.2.0)\n",
      "Requirement already satisfied: tornado>=6.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (6.4.1)\n",
      "Requirement already satisfied: setuptools>=18.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (69.5.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.18.1)\n",
      "Requirement already satisfied: decorator in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (5.1.1)\n",
      "Requirement already satisfied: pickleshare in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.5)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (3.0.20)\n",
      "Requirement already satisfied: pygments in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.15.1)\n",
      "Requirement already satisfied: backcall in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.0)\n",
      "Requirement already satisfied: pexpect>4.3 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.8.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from jinja2>=3->branca>=0.5.0->ipyleaflet) (2.0.1)\n",
      "Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.17.3)\n",
      "Requirement already satisfied: jupyter-core in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.11.2)\n",
      "Requirement already satisfied: notebook>=4.4.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (6.4.12)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.3)\n",
      "Requirement already satisfied: attrs>=17.4.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (21.4.0)\n",
      "Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.20.0)\n",
      "Requirement already satisfied: entrypoints in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyleaflet) (0.4)\n",
      "Requirement already satisfied: argon2-cffi in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (20.1.0)\n",
      "Requirement already satisfied: nbconvert>=5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (6.4.4)\n",
      "Requirement already satisfied: Send2Trash>=1.8.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.8.0)\n",
      "Requirement already satisfied: terminado>=0.8.3 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.17.1)\n",
      "Requirement already satisfied: prometheus-client in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.14.1)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.2.5)\n",
      "Requirement already satisfied: mistune<2,>=0.8.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.8.4)\n",
      "Requirement already satisfied: jupyterlab-pygments in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.1.2)\n",
      "Requirement already satisfied: bleach in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.1.0)\n",
      "Requirement already satisfied: pandocfilters>=1.4.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.5.0)\n",
      "Requirement already satisfied: testpath in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.6.0)\n",
      "Requirement already satisfied: defusedxml in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.7.1)\n",
      "Requirement already satisfied: beautifulsoup4 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (4.12.3)\n",
      "Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.5.13)\n",
      "Requirement already satisfied: cffi>=1.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (1.15.1)\n",
      "Requirement already satisfied: pycparser in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from cffi>=1.0.0->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.21)\n",
      "Requirement already satisfied: soupsieve>1.2 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (2.3.1)\n",
      "Requirement already satisfied: webencodings in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from bleach->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets<9,>=7.6.0->ipyleaflet) (0.5.1)\n",
      "Using cached geopandas-1.0.1-py3-none-any.whl (323 kB)\n",
      "Using cached ipyleaflet-0.19.2-py3-none-any.whl (31 kB)\n",
      "Using cached branca-0.7.2-py3-none-any.whl (25 kB)\n",
      "Using cached jupyter_leaflet-0.19.2-py3-none-any.whl (1.1 MB)\n",
      "Using cached traittypes-0.2.1-py2.py3-none-any.whl (8.6 kB)\n",
      "Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)\n",
      "Building wheels for collected packages: pyogrio\n",
      "  Building wheel for pyogrio (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mBuilding wheel for pyogrio \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[151 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m running bdist_wheel\n",
      "  \u001b[31m   \u001b[0m running build\n",
      "  \u001b[31m   \u001b[0m running build_py\n",
      "  \u001b[31m   \u001b[0m creating build\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_version.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/raw.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/util.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/geopandas.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/errors.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_compat.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_env.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/conftest.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_raw_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_geopandas_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_path.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_arrow.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m writing pyogrio.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to pyogrio.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing requirements to pyogrio.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to pyogrio.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m reading manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m reading manifest template 'MANIFEST.in'\n",
      "  \u001b[31m   \u001b[0m adding license file 'LICENSE'\n",
      "  \u001b[31m   \u001b[0m writing manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-me5i8fu7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'pyogrio.tests.fixtures' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-me5i8fu7/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:218: _Warning: Package 'pyogrio.tests.fixtures.naturalearth_lowres' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures.naturalearth_lowres' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures.naturalearth_lowres' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures.naturalearth_lowres' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures.naturalearth_lowres' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/arrow_bridge.h -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/README.md -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/poly_not_enough_points.shp.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/sample.osm.pbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime_tz.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_fgdb.gdb.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_gpkg_nulls.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_multisurface.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_nested.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_ogr_types_list.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.cpg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.dbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.prj -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shp -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m UPDATING build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py\n",
      "  \u001b[31m   \u001b[0m set build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py to '0.9.0'\n",
      "  \u001b[31m   \u001b[0m running build_ext\n",
      "  \u001b[31m   \u001b[0m building 'pyogrio._err' extension\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -Ipyogrio -I/opt/homebrew/Cellar/gdal/3.7.2/include -I/Users/piotr/opt/anaconda3/include/python3.10 -c pyogrio/_err.c -o build/temp.macosx-10.9-x86_64-cpython-310/pyogrio/_err.o\n",
      "  \u001b[31m   \u001b[0m xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "  \u001b[31m   \u001b[0m error: command '/usr/bin/clang' failed with exit code 1\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[31m  ERROR: Failed building wheel for pyogrio\u001b[0m\u001b[31m\n",
      "\u001b[0mFailed to build pyogrio\n",
      "\u001b[31mERROR: Could not build wheels for pyogrio, which is required to install pyproject.toml-based projects\u001b[0m\u001b[31m\n",
      "\u001b[0m"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<owslib.feature.wfs100.WebFeatureService_1_0_0 at 0x7fc63921e590>"
      ]
     },
     "execution_count": 50,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "!pip install owslib geopandas matplotlib ipyleaflet\n",
    "from owslib.wfs import WebFeatureService\n",
    "wfs = WebFeatureService(url='https://ows.emodnet-bathymetry.eu/wfs')\n",
    "wfs"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'1.0.0'"
      ]
     },
     "execution_count": 51,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "[operation.name for operation in wfs.operations]\n",
    "wfs.version"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['emodnet:download_tiles',\n",
       " 'emodnet:contours',\n",
       " 'emodnet:hr_bathymetry_area',\n",
       " 'emodnet:quality_index',\n",
       " 'world:sea_names',\n",
       " 'emodnet:source_references',\n",
       " 'gebco:undersea_features']"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "list(wfs.contents)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "ename": "ServiceException",
     "evalue": "Feature type :e unknown",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mServiceException\u001b[0m                          Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/ipykernel_55252/2588606580.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mwfs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_schema\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'emodnet:contours'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwfs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetfeature\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtypename\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'emodnet:contours'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbbox\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m54.521\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m7.084\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m58.692\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m15.196\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msrsname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'urn:x-ogc:def:crs:EPSG:4326'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.10/site-packages/owslib/feature/wfs100.py\u001b[0m in \u001b[0;36mgetfeature\u001b[0;34m(self, typename, filter, bbox, featureid, featureversion, propertyname, maxfeatures, srsname, outputFormat, method, startindex)\u001b[0m\n\u001b[1;32m    325\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mtree\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtag\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"{%s}ServiceExceptionReport\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mOGC_NAMESPACE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    326\u001b[0m                     \u001b[0mse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtree\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfind\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnspath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"ServiceException\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mOGC_NAMESPACE\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 327\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mServiceException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstrip\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    328\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0mBytesIO\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    329\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mServiceException\u001b[0m: Feature type :e unknown"
     ]
    }
   ],
   "source": [
    "wfs.get_schema('emodnet:contours')\n",
    "response = wfs.getfeature(typename='emodnet:contours', bbox=(54.521,7.084,58.692,15.196), srsname='urn:x-ogc:def:crs:EPSG:4326')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [
    {
     "ename": "ServiceException",
     "evalue": "Feature type :e unknown",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mServiceException\u001b[0m                          Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/ipykernel_55252/3538351775.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mwfs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetfeature\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtypename\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"emodnet:contours\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbbox\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m54.521\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m7.084\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m58.692\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;36m15.196\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.10/site-packages/owslib/feature/wfs100.py\u001b[0m in \u001b[0;36mgetfeature\u001b[0;34m(self, typename, filter, bbox, featureid, featureversion, propertyname, maxfeatures, srsname, outputFormat, method, startindex)\u001b[0m\n\u001b[1;32m    325\u001b[0m                 \u001b[0;32mif\u001b[0m \u001b[0mtree\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtag\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"{%s}ServiceExceptionReport\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0mOGC_NAMESPACE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    326\u001b[0m                     \u001b[0mse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtree\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfind\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnspath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"ServiceException\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mOGC_NAMESPACE\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 327\u001b[0;31m                     \u001b[0;32mraise\u001b[0m \u001b[0mServiceException\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mse\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtext\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstrip\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    328\u001b[0m                 \u001b[0;32mreturn\u001b[0m \u001b[0mBytesIO\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    329\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mServiceException\u001b[0m: Feature type :e unknown"
     ]
    }
   ],
   "source": [
    "\n",
    "response = wfs.getfeature(typename=\"emodnet:contours\", bbox=(54.521,7.084,58.692,15.196))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "out = open('~/Temp/quality_index.gml', 'wb')\n",
    "out.write(bytes(response.read(), 'UTF-8'))\n",
    "out.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)\")': /simple/geopandas/\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting geopandas\n",
      "  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "Requirement already satisfied: numpy>=1.22 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (1.24.3)\n",
      "Collecting pyogrio>=0.7.2 (from geopandas)\n",
      "  Using cached pyogrio-0.9.0.tar.gz (352 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: packaging in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (21.3)\n",
      "Requirement already satisfied: pandas>=1.4.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas) (1.4.4)\n",
      "Requirement already satisfied: pyproj>=3.3.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/pyproj-3.6.1-py3.10-macosx-10.9-x86_64.egg (from geopandas) (3.6.1)\n",
      "Requirement already satisfied: shapely>=2.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/shapely-2.0.4-py3.10-macosx-10.9-x86_64.egg (from geopandas) (2.0.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pandas>=1.4.0->geopandas) (2024.1)\n",
      "Requirement already satisfied: certifi in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas) (2024.6.2)\n",
      "Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from packaging->geopandas) (3.0.9)\n",
      "Requirement already satisfied: six>=1.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas>=1.4.0->geopandas) (1.16.0)\n",
      "Using cached geopandas-1.0.1-py3-none-any.whl (323 kB)\n",
      "Building wheels for collected packages: pyogrio\n",
      "  Building wheel for pyogrio (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mBuilding wheel for pyogrio \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[151 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m running bdist_wheel\n",
      "  \u001b[31m   \u001b[0m running build\n",
      "  \u001b[31m   \u001b[0m running build_py\n",
      "  \u001b[31m   \u001b[0m creating build\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_version.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/raw.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/util.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/geopandas.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/errors.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_compat.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_env.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/conftest.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_raw_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_geopandas_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_path.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_arrow.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m writing pyogrio.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to pyogrio.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing requirements to pyogrio.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to pyogrio.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m reading manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m reading manifest template 'MANIFEST.in'\n",
      "  \u001b[31m   \u001b[0m adding license file 'LICENSE'\n",
      "  \u001b[31m   \u001b[0m writing manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-2g28pq5y/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:215: _Warning: Package 'pyogrio.tests.fixtures' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-2g28pq5y/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:215: _Warning: Package 'pyogrio.tests.fixtures.naturalearth_lowres' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures.naturalearth_lowres' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures.naturalearth_lowres' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures.naturalearth_lowres' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures.naturalearth_lowres' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/arrow_bridge.h -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/README.md -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/poly_not_enough_points.shp.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/sample.osm.pbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime_tz.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_fgdb.gdb.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_gpkg_nulls.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_multisurface.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_nested.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_ogr_types_list.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.cpg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.dbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.prj -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shp -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m UPDATING build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py\n",
      "  \u001b[31m   \u001b[0m set build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py to '0.9.0'\n",
      "  \u001b[31m   \u001b[0m running build_ext\n",
      "  \u001b[31m   \u001b[0m building 'pyogrio._err' extension\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -Ipyogrio -I/opt/homebrew/Cellar/gdal/3.7.2/include -I/Users/piotr/opt/anaconda3/include/python3.10 -c pyogrio/_err.c -o build/temp.macosx-10.9-x86_64-cpython-310/pyogrio/_err.o\n",
      "  \u001b[31m   \u001b[0m xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "  \u001b[31m   \u001b[0m error: command '/usr/bin/clang' failed with exit code 1\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[31m  ERROR: Failed building wheel for pyogrio\u001b[0m\u001b[31m\n",
      "\u001b[0mFailed to build pyogrio\n",
      "\u001b[31mERROR: Could not build wheels for pyogrio, which is required to install pyproject.toml-based projects\u001b[0m\u001b[31m\n",
      "\u001b[0m"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geopandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/ipykernel_55252/2361855264.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip install geopandas'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mgeopandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mgpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_file\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"~/Temp/dk_coast_quality.geojson\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'geopandas'"
     ]
    }
   ],
   "source": [
    "!pip install geopandas\n",
    "import geopandas as gpd\n",
    "df = gpd.read_file(\"~/Temp/dk_coast_quality.geojson\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)\")': /simple/geoplot/\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting geoplot\n",
      "  Downloading geoplot-0.5.1-py3-none-any.whl.metadata (1.7 kB)\n",
      "Requirement already satisfied: matplotlib>=3.1.2 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geoplot) (3.8.4)\n",
      "Requirement already satisfied: seaborn in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geoplot) (0.11.2)\n",
      "Requirement already satisfied: pandas in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geoplot) (1.4.4)\n",
      "Collecting geopandas>=0.9.0 (from geoplot)\n",
      "  Using cached geopandas-1.0.1-py3-none-any.whl.metadata (2.2 kB)\n",
      "\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)\")': /simple/cartopy/\u001b[0m\u001b[33m\n",
      "\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)\")': /simple/cartopy/\u001b[0m\u001b[33m\n",
      "\u001b[0mCollecting cartopy (from geoplot)\n",
      "  Downloading Cartopy-0.23.0-cp310-cp310-macosx_10_9_x86_64.whl.metadata (8.0 kB)\n",
      "Collecting mapclassify>=2.1 (from geoplot)\n",
      "  Downloading mapclassify-2.8.0-py3-none-any.whl.metadata (2.8 kB)\n",
      "Collecting contextily>=1.0.0 (from geoplot)\n",
      "  Downloading contextily-1.6.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "Collecting geopy (from contextily>=1.0.0->geoplot)\n",
      "  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)\n",
      "Collecting mercantile (from contextily>=1.0.0->geoplot)\n",
      "  Downloading mercantile-1.2.1-py3-none-any.whl.metadata (4.8 kB)\n",
      "Requirement already satisfied: pillow in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from contextily>=1.0.0->geoplot) (9.2.0)\n",
      "Requirement already satisfied: rasterio in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/rasterio-1.4a3-py3.10-macosx-10.9-x86_64.egg (from contextily>=1.0.0->geoplot) (1.4a3)\n",
      "Requirement already satisfied: requests in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from contextily>=1.0.0->geoplot) (2.32.2)\n",
      "Requirement already satisfied: joblib in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from contextily>=1.0.0->geoplot) (1.1.0)\n",
      "Requirement already satisfied: xyzservices in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from contextily>=1.0.0->geoplot) (2022.9.0)\n",
      "Requirement already satisfied: numpy>=1.22 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas>=0.9.0->geoplot) (1.24.3)\n",
      "Collecting pyogrio>=0.7.2 (from geopandas>=0.9.0->geoplot)\n",
      "  Using cached pyogrio-0.9.0.tar.gz (352 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h  Preparing metadata (pyproject.toml) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: packaging in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from geopandas>=0.9.0->geoplot) (21.3)\n",
      "Requirement already satisfied: pyproj>=3.3.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/pyproj-3.6.1-py3.10-macosx-10.9-x86_64.egg (from geopandas>=0.9.0->geoplot) (3.6.1)\n",
      "Requirement already satisfied: shapely>=2.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/shapely-2.0.4-py3.10-macosx-10.9-x86_64.egg (from geopandas>=0.9.0->geoplot) (2.0.4)\n",
      "Requirement already satisfied: networkx>=2.7 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from mapclassify>=2.1->geoplot) (3.2.1)\n",
      "Requirement already satisfied: scikit-learn>=1.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from mapclassify>=2.1->geoplot) (1.0.2)\n",
      "Requirement already satisfied: scipy>=1.8 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from mapclassify>=2.1->geoplot) (1.9.1)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (1.2.0)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (4.25.0)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (1.4.4)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (3.0.9)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from matplotlib>=3.1.2->geoplot) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pandas->geoplot) (2024.1)\n",
      "Collecting pyshp>=2.3 (from cartopy->geoplot)\n",
      "  Using cached pyshp-2.3.1-py2.py3-none-any.whl.metadata (55 kB)\n",
      "Requirement already satisfied: certifi in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from pyogrio>=0.7.2->geopandas>=0.9.0->geoplot) (2024.6.2)\n",
      "Requirement already satisfied: six>=1.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.2->geoplot) (1.16.0)\n",
      "Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from scikit-learn>=1.0->mapclassify>=2.1->geoplot) (2.2.0)\n",
      "Collecting geographiclib<3,>=1.52 (from geopy->contextily>=1.0.0->geoplot)\n",
      "  Downloading geographiclib-2.0-py3-none-any.whl.metadata (1.4 kB)\n",
      "Requirement already satisfied: click>=3.0 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from mercantile->contextily>=1.0.0->geoplot) (8.1.7)\n",
      "Requirement already satisfied: affine in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/affine-2.4.0-py3.10.egg (from rasterio->contextily>=1.0.0->geoplot) (2.4.0)\n",
      "Requirement already satisfied: attrs in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from rasterio->contextily>=1.0.0->geoplot) (21.4.0)\n",
      "Requirement already satisfied: cligj>=0.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/cligj-0.7.2-py3.10.egg (from rasterio->contextily>=1.0.0->geoplot) (0.7.2)\n",
      "Requirement already satisfied: click-plugins in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages/click_plugins-1.1.1-py3.10.egg (from rasterio->contextily>=1.0.0->geoplot) (1.1.1)\n",
      "Requirement already satisfied: setuptools in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from rasterio->contextily>=1.0.0->geoplot) (69.5.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests->contextily>=1.0.0->geoplot) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests->contextily>=1.0.0->geoplot) (3.3)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/piotr/opt/anaconda3/lib/python3.10/site-packages (from requests->contextily>=1.0.0->geoplot) (2.1.0)\n",
      "Downloading geoplot-0.5.1-py3-none-any.whl (28 kB)\n",
      "Downloading contextily-1.6.1-py3-none-any.whl (17 kB)\n",
      "Using cached geopandas-1.0.1-py3-none-any.whl (323 kB)\n",
      "Downloading mapclassify-2.8.0-py3-none-any.whl (58 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m58.9/58.9 kB\u001b[0m \u001b[31m1.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hDownloading Cartopy-0.23.0-cp310-cp310-macosx_10_9_x86_64.whl (10.9 MB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.9/10.9 MB\u001b[0m \u001b[31m3.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hUsing cached pyshp-2.3.1-py2.py3-none-any.whl (46 kB)\n",
      "Downloading geopy-2.4.1-py3-none-any.whl (125 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m125.4/125.4 kB\u001b[0m \u001b[31m2.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hDownloading mercantile-1.2.1-py3-none-any.whl (14 kB)\n",
      "Downloading geographiclib-2.0-py3-none-any.whl (40 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m40.3/40.3 kB\u001b[0m \u001b[31m1.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hBuilding wheels for collected packages: pyogrio\n",
      "  Building wheel for pyogrio (pyproject.toml) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mBuilding wheel for pyogrio \u001b[0m\u001b[1;32m(\u001b[0m\u001b[32mpyproject.toml\u001b[0m\u001b[1;32m)\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[151 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m running bdist_wheel\n",
      "  \u001b[31m   \u001b[0m running build\n",
      "  \u001b[31m   \u001b[0m running build_py\n",
      "  \u001b[31m   \u001b[0m creating build\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_version.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/raw.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/util.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/geopandas.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/errors.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_compat.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_env.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/conftest.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_raw_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_core.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/__init__.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_geopandas_io.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_path.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/test_arrow.py -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests\n",
      "  \u001b[31m   \u001b[0m running egg_info\n",
      "  \u001b[31m   \u001b[0m writing pyogrio.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m writing dependency_links to pyogrio.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m writing requirements to pyogrio.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m writing top-level names to pyogrio.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m reading manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m reading manifest template 'MANIFEST.in'\n",
      "  \u001b[31m   \u001b[0m adding license file 'LICENSE'\n",
      "  \u001b[31m   \u001b[0m writing manifest file 'pyogrio.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-zkk1bxrd/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:215: _Warning: Package 'pyogrio.tests.fixtures' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/pip-build-env-zkk1bxrd/overlay/lib/python3.10/site-packages/setuptools/command/build_py.py:215: _Warning: Package 'pyogrio.tests.fixtures.naturalearth_lowres' is absent from the `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         # Package would be ignored #\n",
      "  \u001b[31m   \u001b[0m         ############################\n",
      "  \u001b[31m   \u001b[0m         Python recognizes 'pyogrio.tests.fixtures.naturalearth_lowres' as an importable package[^1],\n",
      "  \u001b[31m   \u001b[0m         but it is absent from setuptools' `packages` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         This leads to an ambiguous overall configuration. If you want to distribute this\n",
      "  \u001b[31m   \u001b[0m         package, please make sure that 'pyogrio.tests.fixtures.naturalearth_lowres' is explicitly added\n",
      "  \u001b[31m   \u001b[0m         to the `packages` configuration field.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         Alternatively, you can also rely on setuptools' discovery methods\n",
      "  \u001b[31m   \u001b[0m         (for example by using `find_namespace_packages(...)`/`find_namespace:`\n",
      "  \u001b[31m   \u001b[0m         instead of `find_packages(...)`/`find:`).\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package discovery\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         If you don't want 'pyogrio.tests.fixtures.naturalearth_lowres' to be distributed and are\n",
      "  \u001b[31m   \u001b[0m         already explicitly excluding 'pyogrio.tests.fixtures.naturalearth_lowres' via\n",
      "  \u001b[31m   \u001b[0m         `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,\n",
      "  \u001b[31m   \u001b[0m         you can try to use `exclude_package_data`, or `include-package-data=False` in\n",
      "  \u001b[31m   \u001b[0m         combination with a more fine grained `package-data` configuration.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         You can read more about \"package data files\" on setuptools documentation page:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         - https://setuptools.pypa.io/en/latest/userguide/datafiles.html\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         [^1]: For Python, any directory (with suitable naming) can be imported,\n",
      "  \u001b[31m   \u001b[0m               even if it does not contain any `.py` files.\n",
      "  \u001b[31m   \u001b[0m               On the other hand, currently there is no concept of package data\n",
      "  \u001b[31m   \u001b[0m               directory, all directories are treated like packages.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   check.warn(importable)\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_err.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_geometry.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_io.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_ogr.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pxd -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/_vsi.pyx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/arrow_bridge.h -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/README.md -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/poly_not_enough_points.shp.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/sample.osm.pbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_datetime_tz.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_fgdb.gdb.zip -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_gpkg_nulls.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_multisurface.gpkg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_nested.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/test_ogr_types_list.geojson -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures\n",
      "  \u001b[31m   \u001b[0m creating build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.cpg -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.dbf -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.prj -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shp -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m copying pyogrio/tests/fixtures/naturalearth_lowres/naturalearth_lowres.shx -> build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/tests/fixtures/naturalearth_lowres\n",
      "  \u001b[31m   \u001b[0m UPDATING build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py\n",
      "  \u001b[31m   \u001b[0m set build/lib.macosx-10.9-x86_64-cpython-310/pyogrio/_version.py to '0.9.0'\n",
      "  \u001b[31m   \u001b[0m running build_ext\n",
      "  \u001b[31m   \u001b[0m building 'pyogrio._err' extension\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310\n",
      "  \u001b[31m   \u001b[0m creating build/temp.macosx-10.9-x86_64-cpython-310/pyogrio\n",
      "  \u001b[31m   \u001b[0m clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -fPIC -O2 -isystem /Users/piotr/opt/anaconda3/include -Ipyogrio -I/opt/homebrew/Cellar/gdal/3.7.2/include -I/Users/piotr/opt/anaconda3/include/python3.10 -c pyogrio/_err.c -o build/temp.macosx-10.9-x86_64-cpython-310/pyogrio/_err.o\n",
      "  \u001b[31m   \u001b[0m xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun\n",
      "  \u001b[31m   \u001b[0m error: command '/usr/bin/clang' failed with exit code 1\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[31m  ERROR: Failed building wheel for pyogrio\u001b[0m\u001b[31m\n",
      "\u001b[0mFailed to build pyogrio\n",
      "\u001b[31mERROR: Could not build wheels for pyogrio, which is required to install pyproject.toml-based projects\u001b[0m\u001b[31m\n",
      "\u001b[0m"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geoplot'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/ipykernel_55252/703072614.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip install geoplot'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mgeoplot\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mgeoplot\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcrs\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mgcrs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m geoplot.polyplot(\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'geoplot'"
     ]
    }
   ],
   "source": [
    "!pip install geoplot\n",
    "\n",
    "import geoplot\n",
    "import geoplot.crs as gcrs\n",
    "geoplot.polyplot(\n",
    "    df,\n",
    "    projection=gcrs.AlbersEqualArea(),\n",
    "    edgecolor='darkgrey',\n",
    "    facecolor='lightgrey',\n",
    "    linewidth=.3,\n",
    "    figsize=(12, 8)\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'geopandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/4c/mxsj6f9d5_x8cjryn16fb1c40000gn/T/ipykernel_55252/3583912359.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mowslib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwfs\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mWebFeatureService\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mgeopandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mgpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mshapely\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgeometry\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mshape\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mipyleaflet\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mMap\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mGeoData\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbasemaps\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'geopandas'"
     ]
    }
   ],
   "source": [
    "from owslib.wfs import WebFeatureService\n",
    "import geopandas as gpd\n",
    "from shapely.geometry import shape\n",
    "from ipyleaflet import Map, GeoData, basemaps\n",
    "\n",
    "# Define the WFS service URL\n",
    "wfs_url = \"https://ows.emodnet-bathymetry.eu/wfs\"\n",
    "\n",
    "# Initialize the WFS client for version 1.0.0\n",
    "wfs = WebFeatureService(url=wfs_url, version=\"1.0.0\")\n",
    "\n",
    "# List available feature types\n",
    "feature_types = list(wfs.contents)\n",
    "print(\"Available feature types:\", feature_types)\n",
    "\n",
    "# Define the layer (feature type) you want to query\n",
    "layer = \"your-layer-name-here\"\n",
    "\n",
    "# Define the BBOX covering Denmark (approximate coordinates: minx, miny, maxx, maxy)\n",
    "bbox = (8.0, 54.5, 15.0, 57.8)\n",
    "\n",
    "# Perform a GetFeature request with the BBOX filter\n",
    "response = wfs.getfeature(\n",
    "    typename=layer,\n",
    "    bbox=bbox,\n",
    "    outputFormat=\"json\"  # You can specify the format (e.g., \"json\", \"gml\", etc.)\n",
    ")\n",
    "\n",
    "# Read the response data (assumes JSON output)\n",
    "features = response.read()\n",
    "\n",
    "# Convert the response to a GeoDataFrame\n",
    "features_dict = json.loads(features)\n",
    "features_gdf = gpd.GeoDataFrame.from_features(features_dict['features'])\n",
    "\n",
    "# Check the coordinate reference system (CRS)\n",
    "if features_gdf.crs is None:\n",
    "    features_gdf.set_crs(epsg=4326, inplace=True)  # Assuming WGS 84 (EPSG:4326)\n",
    "\n",
    "# Display the first few rows of the GeoDataFrame\n",
    "print(features_gdf.head())\n",
    "\n",
    "# Visualize the data on a map using ipyleaflet\n",
    "center = [55.6761, 12.5683]  # Center map on Copenhagen, Denmark\n",
    "\n",
    "m = Map(center=center, zoom=6, basemap=basemaps.OpenStreetMap.Mapnik)\n",
    "\n",
    "geo_data = GeoData(geo_dataframe=features_gdf, style={'color': 'blue', 'opacity': 1, 'weight': 1.5},\n",
    "                   hover_style={'color': 'red', 'fillOpacity': 0.7},\n",
    "                   name=\"WFS Layer\")\n",
    "\n",
    "m.add_layer(geo_data)\n",
    "m\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
